all:
	@setterm -term linux -back black -fore red
	@echo "#########################################"
	@setterm -term linux -back black -fore white
	gcc main.c -o starcraft -pthread -std=c99

c:
	@setterm -term linux -back black -fore white