all:
	${MAKE} complile || ${MAKE} c

complile:
	@clear
	@setterm -term linux -back black -fore red
	@echo "#########################################"
	@setterm -term linux -back black -fore white

	gcc main.c -o starcraft -pthread -std=c99

	@setterm -term linux -back black -fore red
	@echo "#########################################"
	@setterm -term linux -back black -fore white
c:
	@setterm -term linux -back black -fore red
	@echo "#########################################"
	@setterm -term linux -back black -fore white