all:
	@setterm -term linux -back black -fore red
	@echo -----------------------------------------
	gcc main.c -o starcraft -pthread -std=c99
	@echo -----------------------------------------

	@setterm -term linux -back black -fore white

c:
	@setterm -term linux -back black -fore white